export const APPLICATION_ERROR_CODES = [
  "AUTHENTICATION_REQUIRED",
  "INVALID_CREDENTIALS",
  "FORBIDDEN",
  "VALIDATION_ERROR",
  "DUPLICATE_ORDER_NUMBER",
  "INVALID_TRANSITION",
  "CONFLICT",
  "CANCELLATION_REASON_REQUIRED",
  "ESTIMATE_LOCKED",
  "TRACKING_INVALID",
  "TRACKING_EXPIRED",
  "TRACKING_REVOKED",
  "PERMISSION_UNAVAILABLE",
] as const;

export type ApplicationErrorCode = (typeof APPLICATION_ERROR_CODES)[number];
